CREATE TABLE IF NOT EXISTS revenues (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(70) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(70) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    date TIMESTAMP
);
